### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'value' of null" in main.js:128

### ISSUE THREAD

**Issue by sepehr** [omniwired/toggl-show-me-the-money#1]
I see the money entry nowhere but in the head timer. Console says there's an error in main.js file:  

![screen shot 2015-03-04 at 9 30 06 pm](https://cloud.githubusercontent.com/assets/23576/6489734/11e5b2d8-c2b6-11e4-83d0-48847b0d4035.png)

``` javascript
var currentInput = document.querySelector(omniToggl.liveTimeSelector).value;
```

_P.S. I'll make a pull request to fix this if I can some free time tomorrow.
P.P.S. You've made a grrrreat extension, thank you._

**Comment by sepehr** [comment]
Starting today, it works no more.

**Comment by omniwired** [comment]
I will have a look at it, the only thing working for me right now is the 'livemoney' element.
(next to the timer)

**Comment by sepehr** [comment]
That one has also stopped working as well.

**Comment by sepehr** [comment]
Sorry to bother you again. Do you have any plan to make this compatible again?

**Comment by lelandsmith** [comment]
I would love to be able to use this plugin. Are there going to be any new updates? Thanks for starting this project!

**Comment by omniwired** [comment]
Please enable this and it will work
http://www.evernote.com/shard/s191/sh/1d7f87c3-bb5c-498e-95a5-2a678c15acee/620b0cb8cfce7837e7c51a00d77f5bfe

**Comment by lelandsmith** [comment]
I have the plugin enabled. This is what I am seeing.
http://prntscr.com/6xbpzd

On Thu, Apr 23, 2015 at 11:26 AM, Juan Manuel Combetto <
notifications@github.com> wrote:

> Please enable this and it will work
> 
> http://www.evernote.com/shard/s191/sh/1d7f87c3-bb5c-498e-95a5-2a678c15acee/620b0cb8cfce7837e7c51a00d77f5bfe
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/omniwired/toggl-show-me-the-money/issues/1#issuecomment-95677662
> .

## 

Leland Smith
503.836.7893
emailleland@gmail.com

**Comment by omniwired** [comment]
there was a bug you need to go to another tab and comeback to toggl..com so it can start, i commited a change that fixes this.
And released version 1.0.5 into the chrome dev store.
Thanks for your help, I couldn't do it without you.

**Comment by lelandsmith** [comment]
Oh great! Thank you. Sorry, one more question. Where is the Chrome _DEV_
store?

On Thu, Apr 23, 2015 at 11:48 AM, Juan Manuel Combetto <
notifications@github.com> wrote:

> there was a bug you need to go to another tab and comeback to toggl..com
> so it can start, i commited a change that fixes this.
> And released version 1.0.5 into the chrome dev store.
> Thanks for your help, I couldn't do it without you.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/omniwired/toggl-show-me-the-money/issues/1#issuecomment-95682555
> .

## 

Leland Smith
503.836.7893
emailleland@gmail.com

**Comment by omniwired** [comment]
sorry i mean chrome app store, is where you installed the extension from.
Google told me there is a 60 minute time until it gets propagated to users. 
 It should update to you automatically,

**Comment by lelandsmith** [comment]
Perfect. Thanks again!

On Thu, Apr 23, 2015 at 12:02 PM, Juan Manuel Combetto <
notifications@github.com> wrote:

> sorry i mean chrome app store, is where you installed the extension from.
> Google told me there is a 60 minute time until it gets propagated to
> users.
> It should update to you automatically,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/omniwired/toggl-show-me-the-money/issues/1#issuecomment-95686746>
> .
>



-- 


Leland Smith
503.836.7893
emailleland@gmail.com

**Comment by sepehr** [comment]
I installed the latest version (updated 23 April) from the app store and it simply does not work. Here's a screenshot:  http://prntscr.com/6xnv5m

**Comment by omniwired** [comment]
did you set up your hourly values here?
chrome://extensions/?options=codkafboehhmcigindhjlocahadicpki
(ext options page)

**Comment by sepehr** [comment]
@omniwired Yes I did.  

It's weird that it works just fine on my office Linux machine. But it fails here, on OS X. (same chrome versions!)

**Comment by omniwired** [comment]
OSX has version 1.0.5 of the extension ?

**Comment by sepehr** [comment]
I'm sure that I've installed the latest version as released in April 23rd. Not sure about the version number since I'm at work now. Will report back as soon as I go home.

**Comment by sepehr** [comment]
Sorry I'm late. The recent changes in 1.0.5 (automatic weekly update, etc.) works perfectly fine on my Linux machine. But absolutely nothing on the OS X using the same version.  

_P.S. I tried flushing chrome cache, enabling the extension on incognito and it failed anyway._
_P.P.S. As this is totally a different problem, do you want me to open a separate issue for it?_
